export const hiraToRomajiList: { [key: string]: string[] } = {
  //んっ⚪︎。
  んっきゃ: ['kkya', 'xtukya', 'ltukya'],
  んっきゅ: ['kkyu', 'xtukyu', 'ltukyu'],
  んっきょ: ['kkyo', 'xtukyo', 'ltukyo'],
  んっしゃ: ['ssha', 'xtusha', 'ltusha'],
  んっしゅ: ['sshu', 'xtushu', 'ltushu'],
  んっしょ: ['ssho', 'xtusho', 'ltusho'],
  んっちゃ: ['ccha', 'xtucha', 'ltucha'],
  んっちゅ: ['cchu', 'xtuchu', 'ltuchu'],
  んっちょ: ['ccho', 'xtucho', 'ltucho'],
  んっにゃ: ['nnya', 'xtunya', 'ltunya'],
  んっにゅ: ['nnyu', 'xtunyu', 'ltunyu'],
  んっにょ: ['nnyo', 'xtunyo', 'ltunyo'],
  んっひゃ: ['hhya', 'xtuhya', 'ltuhya'],
  んっひゅ: ['hhyu', 'xtuhyu', 'ltuhyu'],
  んっひょ: ['hhyo', 'xtuhyo', 'ltuhyo'],
  んっみゃ: ['mmya', 'xtumya', 'ltumya'],
  んっみゅ: ['mmyu', 'xtumyu', 'ltumyu'],
  んっみょ: ['mmyo', 'xtumyo', 'ltumyo'],
  んっりゃ: ['rrya', 'xturya', 'lturya'],
  んっりゅ: ['rryu', 'xturyu', 'lturyu'],
  んっりょ: ['rryo', 'xturyo', 'lturyo'],
  んっふぁ: ['ffa', 'xtufa', 'ltufa'],
  んっふぃ: ['ffi', 'xtufi', 'ltufi'],
  んっふぇ: ['ffe', 'xtufe', 'ltufe'],
  んっふぉ: ['ffo', 'xtufo', 'ltufo'],
  んっゔぁ: ['vva', 'xtuva', 'ltuva'],
  んっゔぃ: ['vi','vuxi','vuli'],
  んっゔぇ: ['ve','vuxe','vule'],
  んっゔぉ: ['vo','vuxo','vulo'],
  んっぎゃ: ['ggya', 'xtugya', 'ltugya'],
  んっぎゅ: ['ggyu', 'xtugyu', 'ltugyu'],
  んっぎょ: ['ggyo', 'xtugyo', 'ltugyo'],
  んっじゃ: ['jja', 'zja', 'xtuja', 'ltuja', 'xja', 'lja'],
  んっじゅ: ['jju', 'zju', 'xtuju', 'ltuju', 'xju', 'lju'],
  んっじょ: ['jjo', 'zjo', 'xtujo', 'ltujo', 'xjo', 'ljo'],
  んっぢゃ: ['ddya', 'xtudya', 'ltudya'],
  んっぢゅ: ['ddyu', 'xtudyu', 'ltudyu'],
  んっぢょ: ['ddyo', 'xtudyo', 'ltudyo'],
  んっびゃ: ['bbya', 'xtubya', 'ltubya'],
  んっびゅ: ['bbyu', 'xtubyu', 'ltubyu'],
  んっびょ: ['bbyo', 'xtubyo', 'ltubyo'],
  んっぴゃ: ['ppya', 'xtupya', 'ltupya'],
  んっぴゅ: ['ppyu', 'xtupyu', 'ltupyu'],
  んっぴょ: ['ppyo', 'xtupyo', 'ltupyo'],

  //んっ⚪︎　//んっ。
  んっあ: ['xtua', 'ltua'],
  んっい: ['xtui', 'ltui', 'tti', 'xti', 'lti'],
  んっう: ['xtuu', 'ltuu', 'ttu', 'xtu', 'ltu'],
  んっえ: ['xtue', 'ltue', 'tte', 'xte', 'lte'],
  んっお: ['xtuo', 'ltuo', 'tto', 'xto', 'lto'],
  んっか: ['kka', 'xtuka', 'ltuka'],
  んっき: ['kki', 'xtuki', 'ltuki'],
  んっく: ['kku', 'xtuku', 'ltuku'],
  んっけ: ['kke', 'xtuke', 'ltuke'],
  んっこ: ['kko', 'xtuko', 'ltuko'],
  んっさ: ['ssa', 'xtusa', 'ltusa'],
  んっし: ['sshi', 'ssi', 'xtushi', 'ltushi', 'xtusi', 'ltusi', 'xtsi', 'ltsu'],
  んっす: ['ssu', 'xtusu', 'ltusu'],
  んっせ: ['sse', 'xtuse', 'ltuse'],
  んっそ: ['sso', 'xtuso', 'ltuso'],
  んった: ['tta', 'xtuta', 'ltuta'],
  んっち: ['cchi', 'tti', 'xtuti', 'ltuti', 'xtuti', 'ltuti', 'xtti', 'ltti'],
  んっつ: ['ttsu', 'xtutsu', 'ltutsu'],
  んって: ['tte', 'xtute', 'ltute'],
  んっと: ['tto', 'xtuto', 'ltuto'],
  んっな: ['nna', 'xtuna', 'ltuna'],
  んっに: ['nni', 'xtuni', 'ltuni'],
  んっぬ: ['nnu', 'xtunu', 'ltunu'],
  んっね: ['nne', 'xtune', 'ltune'],
  んっの: ['nno', 'xtuno', 'ltuno'],
  んっは: ['hha', 'xtuha', 'ltuha'],
  んっひ: ['hhi', 'xtuhi', 'ltuhi'],
  んっふ: ['ffu', 'xtufu', 'ltufu'],
  んっへ: ['hhe', 'xtuhe', 'ltuhe'],
  んっほ: ['hho', 'xtuho', 'ltuho'],
  んっま: ['mma', 'xtuma', 'ltuma'],
  んっみ: ['mmi', 'xtumi', 'ltumi'],
  んっむ: ['mmu', 'xtumu', 'ltumu'],
  んっめ: ['mme', 'xtume', 'ltume'],
  んっも: ['mmo', 'xtumo', 'ltumo'],
  んっや: ['yya', 'xtuya', 'ltuya'],
  んっゆ: ['yyu', 'xtuyu', 'ltuyu'],
  んっよ: ['yyo', 'xtuyo', 'ltuyo'],
  んっら: ['rra', 'xtura', 'ltura'],
  んっり: ['rri', 'xturi', 'lturi'],
  んっる: ['rru', 'xturu', 'lturu'],
  んっれ: ['rre', 'xture', 'lture'],
  んっろ: ['rro', 'xturo', 'lturo'],
  んっわ: ['wwa', 'xtuwa', 'ltuwa'],
  んっを: ['wwo', 'xtuwo', 'ltuwo'],
  んっん: ['nn'],
  んっゔ: ['vvu', 'xtuvu', 'ltuvu'],
  んっが: ['gga', 'xtuga', 'ltuga'],
  んっぎ: ['ggi', 'xtugi', 'ltugi'],
  んっぐ: ['ggu', 'xtugu', 'ltugu'],
  んっげ: ['gge', 'xtuge', 'ltuge'],
  んっご: ['ggo', 'xtugo', 'ltugo'],
  んっざ: ['zza', 'xtuza', 'ltuza'],
  んっじ: ['jji', 'zzi', 'xtuji', 'ltuji', 'xtuzi', 'ltuzi', 'xtji', 'ltji', 'xzi', 'lzi'],
  んっず: ['zzu', 'xtuzu', 'ltuzu'],
  んっぜ: ['zze', 'xtuze', 'ltuze'],
  んっぞ: ['zzo', 'xtuzo', 'ltuzo'],
  んっだ: ['dda', 'xtuda', 'ltuda'],
  んっぢ: ['ddi', 'xtudi', 'ltudi', 'xtdi', 'ltdi', 'xtddi', 'ltddi'],
  んっづ: ['ddu', 'xtudu', 'ltudu', 'xtdu', 'ltdu'],
  んっで: ['dde', 'xtude', 'ltude'],
  んっど: ['ddo', 'xtudo', 'ltudo'],
  んっば: ['bba', 'xtuba', 'ltuba'],
  んっび: ['bbi', 'xtubi', 'ltubi'],
  んっぶ: ['bbu', 'xtubu', 'ltubu'],
  んっべ: ['bbe', 'xtube', 'ltube'],
  んっぼ: ['bbo', 'xtubo', 'ltubo'],
  んっぱ: ['ppa', 'xtupa', 'ltupa'],
  んっぴ: ['ppi', 'xtupi', 'ltupi', 'xtpi', 'ltpi', 'xppi', 'ltppi'],
  んっぷ: ['ppu', 'xtupu', 'ltupu'],
  んっぺ: ['ppe', 'xtupe', 'ltupe'],
  んっぽ: ['ppo', 'xtupo', 'ltupo'],
  んっぁ: ['xxa','lla','xtuxa','xtsuxa','xtula','xtsula','ltuxa','ltsuxa','ltula','ltsula'],
  んっぃ: ['xxi','lli','xtuxi','xtsuxi','xtuli','xtsuli','ltuxi','ltsuxi','ltuli','ltsuli'],
  んっぅ: ['xxu','llu','xtuxu','xtsuxu','xtulu','xtsulu','ltuxu','ltsuxu','ltulu','ltsulu'],
  んっぇ: ['xxe','lle','xtuxe','xtsuxe','xtule','xtsule','ltuxe','ltsuxe','ltule','ltsule'],
  んっぉ: ['xxo','llo','xtuxo','xtsuxo','xtulo','xtsulo','ltuxo','ltsuxo','ltulo','ltsulo'],
  んっヵ: ['xka','lka'],
  んっっ: ['xtu','ltu','xtsu','ltsu'],
  んっゃ: ['xya','lya'],
  んっゅ: ['xyu','lyu'],
  んっょ: ['xyo','lyo'],

  //っ⚪︎。
  っきゃ: ['kkya', 'xtukya', 'ltukya'],
  っきゅ: ['kkyu', 'xtukyu', 'ltukyu'],
  っきょ: ['kkyo', 'xtukyo', 'ltukyo'],
  っしゃ: ['ssha', 'xtusha', 'ltusha'],
  っしゅ: ['sshu', 'xtushu', 'ltushu'],
  っしょ: ['ssho', 'xtusho', 'ltusho'],
  っちゃ: ['ccha', 'xtucha', 'ltucha'],
  っちゅ: ['cchu', 'xtuchu', 'ltuchu'],
  っちょ: ['ccho', 'xtucho', 'ltucho'],
  っにゃ: ['nnya', 'xtunya', 'ltunya'],
  っにゅ: ['nnyu', 'xtunyu', 'ltunyu'],
  っにょ: ['nnyo', 'xtunyo', 'ltunyo'],
  っひゃ: ['hhya', 'xtuhya', 'ltuhya'],
  っひゅ: ['hhyu', 'xtuhyu', 'ltuhyu'],
  っひょ: ['hhyo', 'xtuhyo', 'ltuhyo'],
  っみゃ: ['mmya', 'xtumya', 'ltumya'],
  っみゅ: ['mmyu', 'xtumyu', 'ltumyu'],
  っみょ: ['mmyo', 'xtumyo', 'ltumyo'],
  っりゃ: ['rrya', 'xturya', 'lturya'],
  っりゅ: ['rryu', 'xturyu', 'lturyu'],
  っりょ: ['rryo', 'xturyo', 'lturyo'],
  っふぁ: ['ffa', 'xtufa', 'ltufa'],
  っふぃ: ['ffi', 'xtufi', 'ltufi'],
  っふぇ: ['ffe', 'xtufe', 'ltufe'],
  っふぉ: ['ffo', 'xtufo', 'ltufo'],
  っゔぁ: ['vva', 'xtuva', 'ltuva'],
  っゔぃ: ['vi','vuxi','vuli'],
  っゔぇ: ['ve','vuxe','vule'],
  っゔぉ: ['vo','vuxo','vulo'],
  っぎゃ: ['ggya', 'xtugya', 'ltugya'],
  っぎゅ: ['ggyu', 'xtugyu', 'ltugyu'],
  っぎょ: ['ggyo', 'xtugyo', 'ltugyo'],
  っじゃ: ['jja', 'zja', 'xtuja', 'ltuja', 'xja', 'lja'],
  っじゅ: ['jju', 'zju', 'xtuju', 'ltuju', 'xju', 'lju'],
  っじょ: ['jjo', 'zjo', 'xtujo', 'ltujo', 'xjo', 'ljo'],
  っぢゃ: ['ddya', 'xtudya', 'ltudya'],
  っぢゅ: ['ddyu', 'xtudyu', 'ltudyu'],
  っぢょ: ['ddyo', 'xtudyo', 'ltudyo'],
  っびゃ: ['bbya', 'xtubya', 'ltubya'],
  っびゅ: ['bbyu', 'xtubyu', 'ltubyu'],
  っびょ: ['bbyo', 'xtubyo', 'ltubyo'],
  っぴゃ: ['ppya', 'xtupya', 'ltupya'],
  っぴゅ: ['ppyu', 'xtupyu', 'ltupyu'],
  っぴょ: ['ppyo', 'xtupyo', 'ltupyo'],

  //ん⚪︎。
  んきゃ: ['kya', 'kixya', 'kilya', 'tixya', 'tilya'],
  んきぃ: ['kyi', 'kixyi', 'kilyi', 'tixyi', 'tilyi'],
  んきゅ: ['kyu', 'kixyu', 'kilyu', 'tixyu', 'tilyu'],
  んきぇ: ['kye', 'kixye', 'kilye', 'tixye', 'tilye'],
  んきょ: ['kyo', 'kixyo', 'kilyo', 'tixyo', 'tilyo'],
  んしゃ: ['sha', 'sya', 'sixya', 'silya', 'tixya', 'tilya'],
  んしぃ: ['syi', 'shyi', 'sixyi', 'silyi', 'tixyi', 'tilyi'],
  んしゅ: ['shu', 'syu', 'sixyu', 'silyu', 'tixyu', 'tilyu'],
  んしぇ: ['she', 'sye', 'sixye', 'silye', 'tixye', 'tilye'],
  んしょ: ['sho', 'syo', 'sixyo', 'silyo', 'tixyo', 'tilyo'],
  んちゃ: ['cha', 'tya', 'chixya', 'chilya', 'tixya', 'tilya'],
  んちぃ: ['tyi', 'chixyi', 'chilyi', 'tixyi', 'tilyi'],
  んちゅ: ['chu', 'tyu', 'chixyu', 'chilyu', 'tixyu', 'tilyu'],
  んちぇ: ['che', 'tye', 'chixye', 'chilye', 'tixye', 'tilye'],
  んちょ: ['cho', 'tyo', 'chixyo', 'chilyo', 'tixyo', 'tilyo'],
  んにゃ: ['nya', 'nixya', 'nilya', 'tixya', 'tilya'],
  んにぃ: ['nyi', 'nixyi', 'nilyi', 'tixyi', 'tilyi'],
  んにゅ: ['nyu', 'nixyu', 'nilyu', 'tixyu', 'tilyu'],
  んにぇ: ['nye', 'nixye', 'nilye', 'tixye', 'tilye'],
  んにょ: ['nyo', 'nixyo', 'nilyo', 'tixyo', 'tilyo'],
  んひゃ: ['hya', 'hixya', 'hilya', 'tixya', 'tilya'],
  んひぃ: ['hyi', 'hixyi', 'hilyi', 'tixyi', 'tilyi'],
  んひゅ: ['hyu', 'hixyu', 'hilyu', 'tixyu', 'tilyu'],
  んひぇ: ['hye', 'hixye', 'hilye', 'tixye', 'tilye'],
  んひょ: ['hyo', 'hixyo', 'hilyo', 'tixyo', 'tilyo'],
  んみゃ: ['mya', 'mixya', 'milya', 'tixya', 'tilya'],
  んみぃ: ['myi', 'mixyi', 'milyi', 'tixyi', 'tilyi'],
  んみゅ: ['myu', 'mixyu', 'milyu', 'tixyu', 'tilyu'],
  んみぇ: ['mye', 'mixye', 'milye', 'tixye', 'tilye'],
  んみょ: ['myo', 'mixyo', 'milyo', 'tixyo', 'tilyo'],
  んりゃ: ['rya', 'rixya', 'rilya', 'tixya', 'tilya'],
  んりぃ: ['ryi', 'rixyi', 'rilyi', 'tixyi', 'tilyi'],
  んりゅ: ['ryu', 'rixyu', 'rilyu', 'tixyu', 'tilyu'],
  んりぇ: ['rye', 'rixye', 'rilye', 'tixye', 'tilye'],
  んりょ: ['ryo', 'rixyo', 'rilyo', 'tixyo', 'tilyo'],
  んふぁ: ['fa'],
  んふぃ: ['fi'],
  んふぇ: ['fe'],
  んふぉ: ['fo'],
  んゔぁ: ['va','vuxa','vula'],
  んゔぃ: ['vi','vuxi','vuli'],
  んゔぇ: ['ve','vuxe','vule'],
  んゔぉ: ['vo','vuxo','vulo'],
  んぎゃ: ['gya', 'gixya', 'gilya', 'tixya', 'tilya'],
  んぎぃ: ['gyi', 'gixyi', 'gilyi', 'tixyi', 'tilyi'],
  んぎゅ: ['gyu', 'gixyu', 'gilyu', 'tixyu', 'tilyu'],
  んぎぇ: ['gye', 'gixye', 'gilye', 'tixye', 'tilye'],
  んぎょ: ['gyo', 'gixyo', 'gilyo', 'tixyo', 'tilyo'],
  んじゃ: ['ja', 'zya', 'jixya', 'zixya', 'jilya', 'zilya'],
  んじぃ: ['zyi', 'jyi', 'zixyi', 'jixyi', 'zilyi', 'jilyi'],
  んじゅ: ['ju', 'zyu', 'jixyu', 'zixyu', 'jilyu', 'zilyu'],
  んじぇ: ['je', 'zye', 'jixye', 'zixye', 'jilye', 'zilye'],
  んじょ: ['jo', 'zyo', 'jixyo', 'zixyo', 'jilyo', 'zilyo'],
  んぢゃ: ['dya', 'dixya', 'dilya'],
  んぢぃ: ['dyi', 'dixyi', 'dilyi'],
  んぢゅ: ['dyu', 'dixyu', 'dilyu'],
  んぢぇ: ['dye', 'dixye', 'dilye'],
  んぢょ: ['dyo', 'dixyo', 'dilyo'],
  んびゃ: ['bya', 'bixya', 'bilya'],
  んびぃ: ['byi', 'bixyi', 'bilyi'],
  んびゅ: ['byu', 'bixyu', 'bilyu'],
  んびぇ: ['bye', 'bixye', 'bilye'],
  んびょ: ['byo', 'bixyo', 'bilyo'],
  んぴゃ: ['pya', 'pixya', 'pilya'],
  んぴぃ: ['pyi', 'pixyi', 'pilyi'],
  んぴゅ: ['pyu', 'pixyu', 'pilyu'],
  んぴぇ: ['pye', 'pixye', 'pilye'],
  んぴょ: ['pyo', 'pixyo', 'pilyo'],

  //っ⚪︎
  っあ: ['xtua', 'ltua'],
  っい: ['xtui', 'ltui', 'tti', 'xti', 'lti'],
  っう: ['xtuu', 'ltuu', 'ttu', 'xtu', 'ltu'],
  っえ: ['xtue', 'ltue', 'tte', 'xte', 'lte'],
  っお: ['xtuo', 'ltuo', 'tto', 'xto', 'lto'],
  っか: ['kka', 'xtuka', 'ltuka'],
  っき: ['kki', 'xtuki', 'ltuki'],
  っく: ['kku', 'xtuku', 'ltuku'],
  っけ: ['kke', 'xtuke', 'ltuke'],
  っこ: ['kko', 'xtuko', 'ltuko'],
  っさ: ['ssa', 'xtusa', 'ltusa'],
  っし: ['sshi', 'ssi', 'xtushi', 'ltushi', 'xtusi', 'ltusi', 'xtsi', 'ltsu'],
  っす: ['ssu', 'xtusu', 'ltusu'],
  っせ: ['sse', 'xtuse', 'ltuse'],
  っそ: ['sso', 'xtuso', 'ltuso'],
  った: ['tta', 'xtuta', 'ltuta'],
  っち: ['cchi', 'tti', 'xtuti', 'ltuti', 'xtuti', 'ltuti', 'xtti', 'ltti'],
  っつ: ['ttsu', 'xtutsu', 'ltutsu'],
  って: ['tte', 'xtute', 'ltute'],
  っと: ['tto', 'xtuto', 'ltuto'],
  っな: ['nna', 'xtuna', 'ltuna'],
  っに: ['nni', 'xtuni', 'ltuni'],
  っぬ: ['nnu', 'xtunu', 'ltunu'],
  っね: ['nne', 'xtune', 'ltune'],
  っの: ['nno', 'xtuno', 'ltuno'],
  っは: ['hha', 'xtuha', 'ltuha'],
  っひ: ['hhi', 'xtuhi', 'ltuhi'],
  っふ: ['ffu', 'xtufu', 'ltufu'],
  っへ: ['hhe', 'xtuhe', 'ltuhe'],
  っほ: ['hho', 'xtuho', 'ltuho'],
  っま: ['mma', 'xtuma', 'ltuma'],
  っみ: ['mmi', 'xtumi', 'ltumi'],
  っむ: ['mmu', 'xtumu', 'ltumu'],
  っめ: ['mme', 'xtume', 'ltume'],
  っも: ['mmo', 'xtumo', 'ltumo'],
  っや: ['yya', 'xtuya', 'ltuya'],
  っゆ: ['yyu', 'xtuyu', 'ltuyu'],
  っよ: ['yyo', 'xtuyo', 'ltuyo'],
  っら: ['rra', 'xtura', 'ltura'],
  っり: ['rri', 'xturi', 'lturi'],
  っる: ['rru', 'xturu', 'lturu'],
  っれ: ['rre', 'xture', 'lture'],
  っろ: ['rro', 'xturo', 'lturo'],
  っわ: ['wwa', 'xtuwa', 'ltuwa'],
  っを: ['wwo', 'xtuwo', 'ltuwo'],
  っん: ['nn'],
  っゔ: ['vvu', 'xtuvu', 'ltuvu'],
  っが: ['gga', 'xtuga', 'ltuga'],
  っぎ: ['ggi', 'xtugi', 'ltugi'],
  っぐ: ['ggu', 'xtugu', 'ltugu'],
  っげ: ['gge', 'xtuge', 'ltuge'],
  っご: ['ggo', 'xtugo', 'ltugo'],
  っざ: ['zza', 'xtuza', 'ltuza'],
  っじ: ['jji', 'zzi', 'xtuji', 'ltuji', 'xtuzi', 'ltuzi', 'xtji', 'ltji', 'xzi', 'lzi'],
  っず: ['zzu', 'xtuzu', 'ltuzu'],
  っぜ: ['zze', 'xtuze', 'ltuze'],
  っぞ: ['zzo', 'xtuzo', 'ltuzo'],
  っだ: ['dda', 'xtuda', 'ltuda'],
  っぢ: ['ddi', 'xtudi', 'ltudi', 'xtdi', 'ltdi', 'xtddi', 'ltddi'],
  っづ: ['ddu', 'xtudu', 'ltudu', 'xtdu', 'ltdu'],
  っで: ['dde', 'xtude', 'ltude'],
  っど: ['ddo', 'xtudo', 'ltudo'],
  っば: ['bba', 'xtuba', 'ltuba'],
  っび: ['bbi', 'xtubi', 'ltubi'],
  っぶ: ['bbu', 'xtubu', 'ltubu'],
  っべ: ['bbe', 'xtube', 'ltube'],
  っぼ: ['bbo', 'xtubo', 'ltubo'],
  っぱ: ['ppa', 'xtupa', 'ltupa'],
  っぴ: ['ppi', 'xtupi', 'ltupi', 'xtpi', 'ltpi', 'xppi', 'ltppi'],
  っぷ: ['ppu', 'xtupu', 'ltupu'],
  っぺ: ['ppe', 'xtupe', 'ltupe'],
  っぽ: ['ppo', 'xtupo', 'ltupo'],
  っぁ: ['xxa','lla','xtuxa','xtsuxa','xtula','xtsula','ltuxa','ltsuxa','ltula','ltsula'],
  っぃ: ['xxi','lli','xtuxi','xtsuxi','xtuli','xtsuli','ltuxi','ltsuxi','ltuli','ltsuli'],
  っぅ: ['xxu','llu','xtuxu','xtsuxu','xtulu','xtsulu','ltuxu','ltsuxu','ltulu','ltsulu'],
  っぇ: ['xxe','lle','xtuxe','xtsuxe','xtule','xtsule','ltuxe','ltsuxe','ltule','ltsule'],
  っぉ: ['xxo','llo','xtuxo','xtsuxo','xtulo','xtsulo','ltuxo','ltsuxo','ltulo','ltsulo'],
  っヵ: ['xka','lka'],
  っっ: ['xtu','ltu','xtsu','ltsu'],
  っゃ: ['xya','lya'],
  っゅ: ['xyu','lyu'],
  っょ: ['xyo','lyo'],

  //ん⚪︎
  んあ: ['nna'],
  んい: ['nni'],
  んう: ['nnu'],
  んえ: ['nne'],
  んお: ['o'],
  んか: ['ka'],
  んき: ['ki'],
  んく: ['ku'],
  んけ: ['ke'],
  んこ: ['ko'],
  んさ: ['sa'],
  んし: ['si', 'shi'],
  んす: ['su'],
  んせ: ['se'],
  んそ: ['so'],
  んた: ['ta'],
  んち: ['ti', 'chi'],
  んつ: ['tu', 'tsu'],
  んて: ['te'],
  んと: ['to'],
  んな: ['na'],
  んに: ['ni'],
  んぬ: ['nu'],
  んね: ['ne'],
  んの: ['no'],
  んは: ['ha'],
  んひ: ['hi'],
  んふ: ['hu', 'fu'],
  んへ: ['he'],
  んほ: ['ho'],
  んま: ['ma'],
  んみ: ['mi'],
  んむ: ['mu'],
  んめ: ['me'],
  んも: ['mo'],
  んや: ['ya'],
  んゆ: ['yu'],
  んよ: ['yo'],
  んら: ['ra'],
  んり: ['ri'],
  んる: ['ru'],
  んれ: ['re'],
  んろ: ['ro'],
  んわ: ['wa'],
  んを: ['wo'],
  んん: ['nn', 'n'],
  んゔ: ['vu'],
  んが: ['ga'],
  んぎ: ['gi'],
  んぐ: ['gu'],
  んげ: ['ge'],
  んご: ['go'],
  んざ: ['za'],
  んじ: ['zi', 'ji'],
  んず: ['zu'],
  んぜ: ['ze'],
  んぞ: ['zo'],
  んだ: ['da'],
  んぢ: ['di', 'ji'],
  んづ: ['du', 'zu'],
  んで: ['de'],
  んど: ['do'],
  んば: ['ba'],
  んび: ['bi'],
  んぶ: ['bu'],
  んべ: ['be'],
  んぼ: ['bo'],
  んぱ: ['pa'],
  んぴ: ['pi'],
  んぷ: ['pu'],
  んぺ: ['pe'],
  んぽ: ['po'],
  んぁ: ['xa','la'],
  んぃ: ['xi','li'],
  んぅ: ['xu','lu'],
  んぇ: ['xe','le'],
  んぉ: ['xo','lo'],
  んヵ: ['xka','lka'],
  んっ: ['xtu','ltu','xtsu','ltsu'],
  んゃ: ['xya','lya'],
  んゅ: ['xyu','lyu'],
  んょ: ['xyo','lyo'],

  //⚪︎。
  きゃ: ['kya', 'kixya', 'kilya', 'tixya', 'tilya'],
  きぃ: ['kyi', 'kixyi', 'kilyi', 'tixyi', 'tilyi'],
  きゅ: ['kyu', 'kixyu', 'kilyu', 'tixyu', 'tilyu'],
  きぇ: ['kye', 'kixye', 'kilye', 'tixye', 'tilye'],
  きょ: ['kyo', 'kixyo', 'kilyo', 'tixyo', 'tilyo'],
  しゃ: ['sha', 'sya', 'sixya', 'silya', 'tixya', 'tilya'],
  しぃ: ['syi', 'shyi', 'sixyi', 'silyi', 'tixyi', 'tilyi'],
  しゅ: ['shu', 'syu', 'sixyu', 'silyu', 'tixyu', 'tilyu'],
  しぇ: ['she', 'sye', 'sixye', 'silye', 'tixye', 'tilye'],
  しょ: ['sho', 'syo', 'sixyo', 'silyo', 'tixyo', 'tilyo'],
  ちゃ: ['cha', 'tya', 'chixya', 'chilya', 'tixya', 'tilya'],
  ちぃ: ['tyi', 'chixyi', 'chilyi', 'tixyi', 'tilyi'],
  ちゅ: ['chu', 'tyu', 'chixyu', 'chilyu', 'tixyu', 'tilyu'],
  ちぇ: ['che', 'tye', 'chixye', 'chilye', 'tixye', 'tilye'],
  ちょ: ['cho', 'tyo', 'chixyo', 'chilyo', 'tixyo', 'tilyo'],
  にゃ: ['nya', 'nixya', 'nilya', 'tixya', 'tilya'],
  にぃ: ['nyi', 'nixyi', 'nilyi', 'tixyi', 'tilyi'],
  にゅ: ['nyu', 'nixyu', 'nilyu', 'tixyu', 'tilyu'],
  にぇ: ['nye', 'nixye', 'nilye', 'tixye', 'tilye'],
  にょ: ['nyo', 'nixyo', 'nilyo', 'tixyo', 'tilyo'],
  ひゃ: ['hya', 'hixya', 'hilya', 'tixya', 'tilya'],
  ひぃ: ['hyi', 'hixyi', 'hilyi', 'tixyi', 'tilyi'],
  ひゅ: ['hyu', 'hixyu', 'hilyu', 'tixyu', 'tilyu'],
  ひぇ: ['hye', 'hixye', 'hilye', 'tixye', 'tilye'],
  ひょ: ['hyo', 'hixyo', 'hilyo', 'tixyo', 'tilyo'],
  みゃ: ['mya', 'mixya', 'milya', 'tixya', 'tilya'],
  みぃ: ['myi', 'mixyi', 'milyi', 'tixyi', 'tilyi'],
  みゅ: ['myu', 'mixyu', 'milyu', 'tixyu', 'tilyu'],
  みぇ: ['mye', 'mixye', 'milye', 'tixye', 'tilye'],
  みょ: ['myo', 'mixyo', 'milyo', 'tixyo', 'tilyo'],
  りゃ: ['rya', 'rixya', 'rilya', 'tixya', 'tilya'],
  りぃ: ['ryi', 'rixyi', 'rilyi', 'tixyi', 'tilyi'],
  りゅ: ['ryu', 'rixyu', 'rilyu', 'tixyu', 'tilyu'],
  りぇ: ['rye', 'rixye', 'rilye', 'tixye', 'tilye'],
  りょ: ['ryo', 'rixyo', 'rilyo', 'tixyo', 'tilyo'],
  ふぁ: ['fa'],
  ふぃ: ['fi'],
  ふぇ: ['fe'],
  ふぉ: ['fo'],
  ゔぁ: ['va','vuxa','vula'],
  ゔぃ: ['vi','vuxi','vuli'],
  ゔぇ: ['ve','vuxe','vule'],
  ゔぉ: ['vo','vuxo','vulo'],
  ぎゃ: ['gya', 'gixya', 'gilya', 'tixya', 'tilya'],
  ぎぃ: ['gyi', 'gixyi', 'gilyi', 'tixyi', 'tilyi'],
  ぎゅ: ['gyu', 'gixyu', 'gilyu', 'tixyu', 'tilyu'],
  ぎぇ: ['gye', 'gixye', 'gilye', 'tixye', 'tilye'],
  ぎょ: ['gyo', 'gixyo', 'gilyo', 'tixyo', 'tilyo'],
  じゃ: ['ja', 'zya', 'jixya', 'zixya', 'jilya', 'zilya'],
  じぃ: ['zyi', 'jyi', 'zixyi', 'jixyi', 'zilyi', 'jilyi'],
  じゅ: ['ju', 'zyu', 'jixyu', 'zixyu', 'jilyu', 'zilyu'],
  じぇ: ['je', 'zye', 'jixye', 'zixye', 'jilye', 'zilye'],
  じょ: ['jo', 'zyo', 'jixyo', 'zixyo', 'jilyo', 'zilyo'],
  ぢゃ: ['dya', 'dixya', 'dilya'],
  ぢぃ: ['dyi', 'dixyi', 'dilyi'],
  ぢゅ: ['dyu', 'dixyu', 'dilyu'],
  ぢぇ: ['dye', 'dixye', 'dilye'],
  ぢょ: ['dyo', 'dixyo', 'dilyo'],
  びゃ: ['bya', 'bixya', 'bilya'],
  びぃ: ['byi', 'bixyi', 'bilyi'],
  びゅ: ['byu', 'bixyu', 'bilyu'],
  びぇ: ['bye', 'bixye', 'bilye'],
  びょ: ['byo', 'bixyo', 'bilyo'],
  ぴゃ: ['pya', 'pixya', 'pilya'],
  ぴぃ: ['pyi', 'pixyi', 'pilyi'],
  ぴゅ: ['pyu', 'pixyu', 'pilyu'],
  ぴぇ: ['pye', 'pixye', 'pilye'],
  ぴょ: ['pyo', 'pixyo', 'pilyo'],

  //⚪︎
  あ: ['a'],
  い: ['i'],
  う: ['u'],
  え: ['e'],
  お: ['o'],
  か: ['ka'],
  き: ['ki'],
  く: ['ku'],
  け: ['ke'],
  こ: ['ko'],
  さ: ['sa'],
  し: ['si', 'shi'],
  す: ['su'],
  せ: ['se'],
  そ: ['so'],
  た: ['ta'],
  ち: ['ti', 'chi'],
  つ: ['tu', 'tsu'],
  て: ['te'],
  と: ['to'],
  な: ['na'],
  に: ['ni'],
  ぬ: ['nu'],
  ね: ['ne'],
  の: ['no'],
  は: ['ha'],
  ひ: ['hi'],
  ふ: ['hu', 'fu'],
  へ: ['he'],
  ほ: ['ho'],
  ま: ['ma'],
  み: ['mi'],
  む: ['mu'],
  め: ['me'],
  も: ['mo'],
  や: ['ya'],
  ゆ: ['yu'],
  よ: ['yo'],
  ら: ['ra'],
  り: ['ri'],
  る: ['ru'],
  れ: ['re'],
  ろ: ['ro'],
  わ: ['wa'],
  を: ['wo'],
  ん: ['nn', 'n'],
  ゔ: ['vu'],
  が: ['ga'],
  ぎ: ['gi'],
  ぐ: ['gu'],
  げ: ['ge'],
  ご: ['go'],
  ざ: ['za'],
  じ: ['zi', 'ji'],
  ず: ['zu'],
  ぜ: ['ze'],
  ぞ: ['zo'],
  だ: ['da'],
  ぢ: ['di', 'ji'],
  づ: ['du', 'zu'],
  で: ['de'],
  ど: ['do'],
  ば: ['ba'],
  び: ['bi'],
  ぶ: ['bu'],
  べ: ['be'],
  ぼ: ['bo'],
  ぱ: ['pa'],
  ぴ: ['pi'],
  ぷ: ['pu'],
  ぺ: ['pe'],
  ぽ: ['po'],
  ぁ: ['xa','la'],
  ぃ: ['xi','li'],
  ぅ: ['xu','lu'],
  ぇ: ['xe','le'],
  ぉ: ['xo','lo'],
  ヵ: ['xka','lka'],
  っ: ['xtu','ltu','xtsu','ltsu'],
  ゃ: ['xya','lya'],
  ゅ: ['xyu','lyu'],
  ょ: ['xyo','lyo'],
};
